### ISSUE TITLE
Not displaying map to RViz

### ISSUE THREAD

**Issue by maccers** [NickL77/RPLidar_Hector_SLAM#1]
No errors when running commands, but nothing is being displayed on RViz. " $ rostopic echo slam_out_pose " displays " WARNING: no messages received and simulated time is active.
Is /clock being published? " I am using ubuntu 16.04 and Rplidar A2

**Comment by NickL77** [comment]
Have you taken a look at [this](https://answers.ros.org/question/12083/messages-being-blocked-from-publishing/)?
