### ISSUE TITLE
Wrong map

### ISSUE THREAD

**Issue by ghostaz** [NickL77/RPLidar_Hector_SLAM#2]
Hello. I get broken map, with offset. Can you help me?
![_01_08_2018_01_06_51](https://user-images.githubusercontent.com/15945735/43606222-2ed39ea2-96b4-11e8-9836-060fd1973ec4.png)

ROS Kinetic, RPLidar A1. Ubuntu 16.04.  Raspberry Pi3 as master.

**Comment by NickL77** [comment]
Can you elaborate on the issue? I don't see an issue in the screenshot you shared.
