### ISSUE TITLE
Data not being published to Topics correctly

### ISSUE THREAD

**Issue by AandJ** [NickL77/RPLidar_Hector_SLAM#3]
I Run the node roslaunch rplidar_ros rplidar.launch and can see data being published to the /scan topic, this is visible in rviz when i run the command roslaunch rplidar_ros view_rplidar.launch as shown below.
![screenshot from 2018-10-03 12-50-26](https://user-images.githubusercontent.com/32260011/46408708-eaf00900-c70a-11e8-944a-392a0d6e9271.png)
i then ran the command roslaunch hector_slam_launch tutorial.launch but no data is shown in rviz, i have listed the topics shown below 
![screenshot from 2018-10-03 12-44-27](https://user-images.githubusercontent.com/32260011/46408637-ab292180-c70a-11e8-8f3b-5c162b8a1c71.png)
I echoed /map, but it seems to only publish "-1" which makes me believe there is an error. I echoed other topics but but very few have anything publishes, might it be because /clock has nothing published that it does not work and if so how do i fix this?

Any Ideas as to why this might not work? I am using the A1M8 RPLidar on ROS kinetic, i downloaded your REPO and did not use the original hector slam REPO, i have checked the use_sim_time param and it is set false as it should be.

**Comment by NickL77** [comment]
Just to make sure, you're running `rplidar_ros rplidar.launch` in one terminal, and then `roslaunch hector_slam_launch tutorial.launch` on another terminal concurrently?

If so, are any errors or warnings being shown on the left side in RVIZ (ie. where it shows `Global Status: Warn` in the first image you've attached?

Also, I just tested this locally with the A1M8 on kinetic, and my map topic also only prints out -1's, but I do not have a `/clock` topic.

**Comment by AandJ** [comment]
Thanks, i don't know  why but all of a sudden it started working this morning, i think it is because i had installed ros-kinetic-hector-slam through the terminal yesterday and later removed it but never restarted my PC, now that my pc has restarted and re-freshed i think it is working properly.

To answer your questions i was running them concurrently in two separate terminals and no errors where shown but one warning was which was "no TF data", now that my SLAM is working i no longer have the /clock topic which also makes me believe it was due to it using the wrong package yesterday installed yesterday which was fixed by the restart of my PC.

Once again thank-you for your help
