### ISSUE TITLE
Can use another lidar ?

### ISSUE THREAD

**Issue by sPhaykrew** [NickL77/RPLidar_Hector_SLAM#4]
Can use another lidar like neato xv11 ?

**Comment by NickL77** [comment]
The packages in this repo are specifically for the RPlidar. You can look into the following link to install the packages for the Neato: http://wiki.ros.org/xv_11_laser_driver/Tutorials/Running%20the%20XV-11%20Node

Here's the corresponding github: https://github.com/rohbotics/xv_11_laser_driver

Hector SLAM will work with any lidar that publishes to the /scan topic.
