### ISSUE TITLE
Next frames overlapping in previous frames

### ISSUE THREAD

**Issue by bkmen97** [NickL77/RPLidar_Hector_SLAM#5]
I did follow tutorial in the video, but when rotate the RpLidar A1, Lidar scan map again and the next map frames overlapping the previous map frames, i don't understand where is error. Thanks
![Screenshot from 2019-07-14 11-29-39](https://user-images.githubusercontent.com/41550290/61180016-312ead00-a639-11e9-9333-83ddb24c4720.png)

**Comment by NickL77** [comment]
What video are you referring to? It appears that SLAM is having difficulty localizing where you are so it's overlaying the new scans. My first intuition would be that you're moving the lidar too fast or it's jerking around.

If you are moving it smoothly and slowly and that's still happening, then depending on what you're working on, you can try adding an IMU and either add IMU input to hector_slam or use another algorithm like g_mapping.

**Comment by bkmen97** [comment]
Thanks. I slowly moved and rotated. Then Hector slam worked better. So good.
