### ISSUE TITLE
Can't change base_frame & odom_frame

### ISSUE THREAD

**Issue by lxtrungg** [NickL77/RPLidar_Hector_SLAM#8]
I changed code follow intruction, because I use Orginal Hector-Slam.
But When I type "roslauch hector-slam-launch", rviz appear but nothing show in display of Lidar, I watch in Terminal, base_frame and odom_frame is default, not changed by me.
How I can solve it?
Thanks

**Comment by NickL77** [comment]
Can you send a screenshot of your [tf tree](http://wiki.ros.org/tf)? `rosrun tf view_frames`
